version: '3.9'
services:
  docker-redloader-sotf-server:
    container_name: docker-redloader-sotf-server
    image: tonimacaroniy/docker-redloader-sotf-server:0.7.0
    restart: always
    environment:
      ALWAYS_UPDATE_ON_START: 1
    ports:
      - 8766:8766/udp
      - 27016:27016/udp
      - 9700:9700/udp
    volumes:
      - ./steamcmd:/steamcmd
      - ./game:/sonsoftheforest
      - ./winedata:/winedata
